# Generated by Django 5.2.8 on 2025-11-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTRATION', 'Registration'), ('FILE_UPLOAD', 'File Upload'), ('FILE_DOWNLOAD', 'File Download'), ('FILE_SHARED', 'File Shared'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('UNAUTHORIZED_DOWNLOAD', 'Unauthorized Download'), ('FILE_INTEGRITY_VIOLATION', 'File Integrity Violation'), ('FILE_DECRYPTION_ERROR', 'File Decryption Error'), ('FILE_UPLOAD_ERROR', 'File Upload Error'), ('VIEW_ACCESS', 'View Access')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
